<a href="https://colab.research.google.com/github/piavila/I_ML/blob/main/Lab_32_Pili.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio 2: Armado de un esquema de aprendizaje automático

En el laboratorio final se espera que puedan poner en práctica los conocimientos adquiridos en el curso, trabajando con un conjunto de datos de clasificación.

El objetivo es que se introduzcan en el desarrollo de un esquema para hacer tareas de aprendizaje automático: selección de un modelo, ajuste de hiperparámetros y evaluación.

El conjunto de datos a utilizar está en `./data/loan_data.csv`. Si abren el archivo verán que al principio (las líneas que empiezan con `#`) describen el conjunto de datos y sus atributos (incluyendo el atributo de etiqueta o clase).

Se espera que hagan uso de las herramientas vistas en el curso. Se espera que hagan uso especialmente de las herramientas brindadas por `scikit-learn`.

In [ ]:
import numpy as np
import pandas as pd

# TODO: Agregar las librerías que hagan falta
from sklearn.model_selection import train_test_split

## Carga de datos y división en entrenamiento y evaluación

La celda siguiente se encarga de la carga de datos (haciendo uso de pandas). Estos serán los que se trabajarán en el resto del laboratorio.

In [ ]:
from google.colab import files 
uploaded = files.upload()

Saving loan_data.csv to loan_data (2).csv


In [ ]:
dataset = pd.read_csv("loan_data.csv", comment="#")

# División entre instancias y etiquetas
X, y = dataset.iloc[:, 1:], dataset.TARGET

# división entre entrenamiento y evaluación
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



Documentación:

- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

## Ejercicio 1: Descripción de los Datos y la Tarea

Responder las siguientes preguntas:

1. ¿De qué se trata el conjunto de datos?
2. ¿Cuál es la variable objetivo que hay que predecir? ¿Qué significado tiene?
3. ¿Qué información (atributos) hay disponible para hacer la predicción?
4. ¿Qué atributos imagina ud. que son los más determinantes para la predicción?

**No hace falta escribir código para responder estas preguntas.**

### Ejercicio 1: 

1. El conjunto de datos contiene información sobre el desempeño de préstamos con garantía hipotecaria de 5960 casos.

2. La variable objetivo que hay que predecir se denomina TARGET. Es una variable binaria que indica si el aplicante al préstamo incumplió o fue gravemente moroso. Este resultado ocurrió en 1189 casos (20% del total).

3. La información que hay disponible para hacer esta predicción son 11 atributos que se listan a continuación,

    * TARGET: atributos objetivo. Variable binaria con valores: 1 = cliente no pagó el préstamo; 0 = cliente pagó el préstamo.
    * LOAN: monto de préstamo requerido
    * MORTDUE: monto adeudado en el préstamo pedido
    * VALUE: valor de la propiedad actual
    * YOJ: años en el trabajo actual
    * DEROG: cantidad de informes reprobados
    * DELNQ: cantidad de líneas de créditos no pagas
    * CLAGE: antigüedad (en meses) de la línea de crédito
    * NINQ: cantidad de líneas de créditos actuales
    * CLNO: cantidad de líneas de crédito
    * DEBTINC: cociente entre la deuda y los ingresos del aplicante


4. Los atributos que imaginamos son los más determinantes para la predicción son: TARGET, DEROG, DELINQ, DEBTINC

In [ ]:
#Vemos el dataset
dataset.iloc[:10]

TARGET   LOAN   MORTDUE     VALUE   YOJ  DEROG  DELINQ       CLAGE  NINQ  \
0       0   4700   88026.0  115506.0   6.0    0.0     0.0  182.248332   0.0   
1       0  19300   39926.0  101208.0   4.0    0.0     0.0  140.051638   0.0   
2       0   5700   71556.0   79538.0   2.0    0.0     0.0   92.643085   0.0   
3       0  13000   44875.0   57713.0   0.0    1.0     0.0  184.990324   1.0   
4       0  19300   72752.0  106084.0  11.0    0.0     0.0  193.707100   1.0   
5       0  11500   53651.0   87547.0  18.0    0.0     0.0  191.396887   0.0   
6       0  17200  103519.0  118074.0   0.0    0.0     0.0  102.678612   1.0   
7       0  24200   22763.0   47622.0  23.0    0.0     0.0  126.922691   1.0   
8       0  12600   62493.0   77141.0  13.0    0.0     0.0  266.333101   0.0   
9       0  12300   90006.0  121122.0   9.0    0.0     0.0  133.497541   1.0   

   CLNO    DEBTINC  
0  27.0  29.209023  
1  14.0  31.545694  
2  15.0  41.210012  
3  12.0  28.602076  
4  13.0  30.686106  
5  16.0  34.368651  
6  21.0  41.418353  
7  10.0  23.040945  
8  26.0  27.007872  
9  21.0  36.910482

In [ ]:
#Estudiamos los estadísticos de las columnas
for col in dataset.columns:
    #print(col)
    print('')
    print('*****',col,'*****')
    print('')
    print(dataset[col].describe())


***** TARGET *****

count    1854.000000
mean        0.166667
std         0.372779
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: TARGET, dtype: float64

***** LOAN *****

count     1854.000000
mean     19111.758360
std      11000.345961
min       1700.000000
25%      12000.000000
50%      17000.000000
75%      23900.000000
max      89800.000000
Name: LOAN, dtype: float64

***** MORTDUE *****

count      1854.000000
mean      76316.051780
std       46227.026585
min        5627.000000
25%       48984.750000
50%       67201.000000
75%       93731.500000
max      399412.000000
Name: MORTDUE, dtype: float64

***** VALUE *****

count      1854.000000
mean     107321.088457
std       56039.685066
min       21144.000000
25%       70787.250000
50%       94198.000000
75%      122976.250000
max      512650.000000
Name: VALUE, dtype: float64

***** YOJ *****

count    1854.000000
mean        8.900216
std         7.552677
min        

## Ejercicio 2: Predicción con Modelos Lineales

En este ejercicio se entrenarán modelos lineales de clasificación para predecir la variable objetivo.

Para ello, deberán utilizar la clase SGDClassifier de scikit-learn.

Documentación:
- https://scikit-learn.org/stable/modules/sgd.html
- https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html


### Ejercicio 2.1: SGDClassifier con hiperparámetros por defecto

Entrenar y evaluar el clasificador SGDClassifier usando los valores por omisión de scikit-learn para todos los parámetros. Únicamente **fijar la semilla aleatoria** para hacer repetible el experimento.

Evaluar sobre el conjunto de **entrenamiento** y sobre el conjunto de **evaluación**, reportando:
- Accuracy
- Precision
- Recall
- F1
- matriz de confusión

In [ ]:
# Importamos SGDClassifier
from sklearn.linear_model import SGDClassifier
# Creamos el clasificador 'clf' fijando la semilla aleatoria
clf = SGDClassifier(random_state=0)     #You need to fix this value so the results are repeatable so set random_state=0 or whatever favourite number you want
# Evaluamos sobre el conjunto de entrenamiento
clf.fit(X_train, y_train)

SGDClassifier(random_state=0)

#### Accuracy, precision, recall, F1

In [ ]:
# Importamos 'accuracy_score', precision_score', 'recall_score', 'f1_score'
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


# Evaluamos sobre el conjunto de entrenamiento
Acc_Train = accuracy_score( y_train , clf.predict(X_train) )

# Evaluamos sobre el conjunto de validación
Acc_Test = accuracy_score( y_test , clf.predict(X_test) )

# Evaluamos sobre el conjunto de entrenamiento
Pre_Train = precision_score(y_train, clf.predict(X_train), average='micro')

# Evaluamos sobre el conjunto de validacion
Pre_Test= precision_score(y_test, clf.predict(X_test), average='micro')

# Evaluamos sobre el conjunto de entrenamiento
Rec_Train = recall_score(y_train, clf.predict(X_train))

# Evaluamos sobre el conjunto de validacion
Rec_Test= recall_score(y_test, clf.predict(X_test) ) 

# Evaluamos sobre el conjunto de entrenamiento
F1_Train = f1_score(y_train, clf.predict(X_train), average='weighted')

# Evaluamos sobre el conjunto de validacion
F1_Test= f1_score(y_test, clf.predict(X_test), average='weighted')

print("Acurracy for train vlues:", Acc_Train)
print("Acurracy for test vlues:", Acc_Test)
print("Precision for train vlues:",Pre_Train)
print("Precision for test vlues:", Pre_Test)
print("Recall for train vlues:",Rec_Train)
print("Recall for train vlues:", Rec_Test)
print("F1 for train vlues:",F1_Train)
print("F1 for train vlues:",F1_Test)

Acurracy for train vlues: 0.8307484828051247
Acurracy for test vlues: 0.8436657681940701
Precision for train vlues: 0.8307484828051247
Precision for test vlues: 0.8436657681940701
Recall for train vlues: 0.0
Recall for train vlues: 0.0
F1 for train vlues: 0.7539463210430304
F1 for train vlues: 0.772126858025567


In [ ]:
# Importamos 'classification_report'

from sklearn.metrics import classification_report
print(classification_report(y_train, clf.predict(X_train), zero_division=0))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91      1232
           1       0.00      0.00      0.00       251

    accuracy                           0.83      1483
   macro avg       0.42      0.50      0.45      1483
weighted avg       0.69      0.83      0.75      1483



#### Matriz de confusión

In [ ]:
# importo 'confusion_matrix'
from sklearn.metrics import confusion_matrix

# evaluo sobre el conjunto de entrenamiento
confusion_matrix(y_train, clf.predict(X_train))

# evaluo sobre el conjunto de validacion
confusion_matrix(y_test, clf.predict(X_test)) 


array([[313,   0],
       [ 58,   0]])

### Ejercicio 2.2: Ajuste de Hiperparámetros

Seleccionar valores para los hiperparámetros principales del SGDClassifier. Como mínimo, probar diferentes funciones de loss, tasas de entrenamiento y tasas de regularización.

Para ello, usar grid-search y 5-fold cross-validation sobre el conjunto de entrenamiento para explorar muchas combinaciones posibles de valores.

Reportar accuracy promedio y varianza para todas las configuraciones.

Para la mejor configuración encontrada, evaluar sobre el conjunto de **entrenamiento** y sobre el conjunto de **evaluación**, reportando:
- Accuracy
- Precision
- Recall
- F1
- matriz de confusión

Documentación:
- https://scikit-learn.org/stable/modules/grid_search.html
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
#Importamos GridSearchCV
from sklearn.model_selection import GridSearchCV

In [ ]:
# Definimos el espacio de parámetros
param_grid = {'loss': ('hinge','log','perceptron'),
              'penalty': ('l2', 'l1', 'elasticnet'),
              'learning_rate': ('constant','optimal','invscaling','adaptive')}

# Creamos el clasificador 'clf' fijando la semilla aleatoria
clf = SGDClassifier(random_state=0,eta0=0.01)

# Creamos el clasificador 'cv' usando GridSearchCV
cv = GridSearchCV(clf,param_grid,cv=5)

In [ ]:
#Evaluamos sobre el conjunto de entrenamiento
cv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SGDClassifier(eta0=0.01, random_state=0),
             param_grid={'learning_rate': ('constant', 'optimal', 'invscaling',
                                           'adaptive'),
                         'loss': ('hinge', 'log', 'perceptron'),
                         'penalty': ('l2', 'l1', 'elasticnet')})

In [ ]:
# Reportamos accuracy promedio y varianza para todas las configuraciones.
results = cv.cv_results_
params = results['params']
means = results['mean_test_score']
stds = results['std_test_score']
rank = results['rank_test_score']
for mean, std, params in zip(means, stds, params):
    print("Exactitud: %0.2f (+/-%0.02f) para los parámetros %r" % (mean, std ** 2, params))

Exactitud: 0.70 (+/-0.06) para los parámetros {'learning_rate': 'constant', 'loss': 'hinge', 'penalty': 'l2'}
Exactitud: 0.72 (+/-0.05) para los parámetros {'learning_rate': 'constant', 'loss': 'hinge', 'penalty': 'l1'}
Exactitud: 0.70 (+/-0.06) para los parámetros {'learning_rate': 'constant', 'loss': 'hinge', 'penalty': 'elasticnet'}
Exactitud: 0.55 (+/-0.08) para los parámetros {'learning_rate': 'constant', 'loss': 'log', 'penalty': 'l2'}
Exactitud: 0.70 (+/-0.06) para los parámetros {'learning_rate': 'constant', 'loss': 'log', 'penalty': 'l1'}
Exactitud: 0.69 (+/-0.07) para los parámetros {'learning_rate': 'constant', 'loss': 'log', 'penalty': 'elasticnet'}
Exactitud: 0.70 (+/-0.06) para los parámetros {'learning_rate': 'constant', 'loss': 'perceptron', 'penalty': 'l2'}
Exactitud: 0.72 (+/-0.05) para los parámetros {'learning_rate': 'constant', 'loss': 'perceptron', 'penalty': 'l1'}
Exactitud: 0.70 (+/-0.06) para los parámetros {'learning_rate': 'constant', 'loss': 'perceptron', 'p

In [ ]:
# Vemos cuáles son los mejores parámetros
best_model = cv.best_estimator_
cv.best_params_

{'learning_rate': 'optimal', 'loss': 'hinge', 'penalty': 'l2'}

In [ ]:
# Armamos el clasificador con los mejores parámetros encontrados
clf2 = SGDClassifier(loss='hinge',penalty='l2',learning_rate='optimal',random_state=0)

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
clf2.fit(X_train, y_train)

SGDClassifier(random_state=0)

#### Accuracy, precision, recall, F1

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
Acc_Train2 = accuracy_score( y_train , clf2.predict(X_train) )

# Evaluamos sobre el conjunto de validación
Acc_Test2 = accuracy_score( y_test , clf2.predict(X_test) )

# Evaluamos sobre el conjunto de entrenamiento
Pre_Train2 = precision_score(y_train, clf2.predict(X_train), average='micro')

# Evaluamos sobre el conjunto de validacion
Pre_Test2 = precision_score(y_test, clf2.predict(X_test), average='micro')

# Evaluamos sobre el conjunto de entrenamiento
Rec_Train2 = recall_score(y_train, clf2.predict(X_train))

# Evaluamos sobre el conjunto de validacion
Rec_Test2 = recall_score(y_test, clf2.predict(X_test) ) 

# Evaluamos sobre el conjunto de entrenamiento
F1_Train2 = f1_score(y_train, clf2.predict(X_train), average='weighted')

# Evaluamos sobre el conjunto de validacion
F1_Test2 = f1_score(y_test, clf2.predict(X_test), average='weighted')

print("Acurracy for train vlues:", Acc_Train2)
print("Acurracy for test vlues:", Acc_Test2)
print("Precision for train vlues:",Pre_Train2)
print("Precision for test vlues:", Pre_Test2)
print("Recall for train vlues:",Rec_Train2)
print("Recall for train vlues:", Rec_Test2)
print("F1 for train vlues:",F1_Train2)
print("F1 for train vlues:",F1_Test2)

Acurracy for train vlues: 0.8307484828051247
Acurracy for test vlues: 0.8436657681940701
Precision for train vlues: 0.8307484828051247
Precision for test vlues: 0.8436657681940701
Recall for train vlues: 0.0
Recall for train vlues: 0.0
F1 for train vlues: 0.7539463210430304
F1 for train vlues: 0.772126858025567


#### Matriz de confusión

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
confusion_matrix(y_train, clf2.predict(X_train))

# Evaluamos sobre el conjunto de validacion
confusion_matrix(y_test, clf2.predict(X_test))  

array([[313,   0],
       [ 58,   0]])

## Ejercicio 3: Árboles de Decisión

En este ejercicio se entrenarán árboles de decisión para predecir la variable objetivo.

Para ello, deberán utilizar la clase DecisionTreeClassifier de scikit-learn.

Documentación:
- https://scikit-learn.org/stable/modules/tree.html
  - https://scikit-learn.org/stable/modules/tree.html#tips-on-practical-use
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
- https://scikit-learn.org/stable/auto_examples/tree/plot_unveil_tree_structure.html

### Ejercicio 3.1: DecisionTreeClassifier con hiperparámetros por defecto

Entrenar y evaluar el clasificador DecisionTreeClassifier usando los valores por omisión de scikit-learn para todos los parámetros. Únicamente **fijar la semilla aleatoria** para hacer repetible el experimento.

Evaluar sobre el conjunto de **entrenamiento** y sobre el conjunto de **evaluación**, reportando:
- Accuracy
- Precision
- Recall
- F1
- matriz de confusión


#### DecisionTreeClassifier

In [ ]:
# Imporamos DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

# Creamos el clasificador 'clf3' fijando la semilla aleatoria
clf3 = DecisionTreeClassifier(random_state=0)

# Evaluamos sobre el conjunto de entrenamiento
clf3.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

#### Accuracy, precision, recall, F1

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
Acc_Train3 = accuracy_score( y_train , clf3.predict(X_train) )

# Evaluamos sobre el conjunto de validación
Acc_Test3 = accuracy_score( y_test , clf3.predict(X_test) )

# Evaluamos sobre el conjunto de entrenamiento
Pre_Train3 = precision_score(y_train, clf3.predict(X_train), average='micro')

# Evaluamos sobre el conjunto de validacion
Pre_Test3 = precision_score(y_test, clf3.predict(X_test), average='micro')

# Evaluamos sobre el conjunto de entrenamiento
Rec_Train3 = recall_score(y_train, clf3.predict(X_train))

# Evaluamos sobre el conjunto de validacion
Rec_Test3 = recall_score(y_test, clf3.predict(X_test) ) 

# Evaluamos sobre el conjunto de entrenamiento
F1_Train3 = f1_score(y_train, clf3.predict(X_train), average='weighted')

# Evaluamos sobre el conjunto de validacion
F1_Test3= f1_score(y_test, clf3.predict(X_test), average='weighted')

print("Acurracy for train vlues:", Acc_Train3)
print("Acurracy for test vlues:", Acc_Test3)
print("Precision for train vlues:",Pre_Train3)
print("Precision for test vlues:", Pre_Test3)
print("Recall for train vlues:",Rec_Train3)
print("Recall for train vlues:", Rec_Test3)
print("F1 for train vlues:",F1_Train3)
print("F1 for train vlues:",F1_Test3)

Acurracy for train vlues: 1.0
Acurracy for test vlues: 0.8814016172506739
Precision for train vlues: 1.0
Precision for test vlues: 0.8814016172506739
Recall for train vlues: 1.0
Recall for train vlues: 0.6379310344827587
F1 for train vlues: 1.0
F1 for train vlues: 0.8822166267801062


#### Matriz de confusión

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
confusion_matrix(y_train, clf3.predict(X_train))

# Evaluamos sobre el conjunto de validacion
confusion_matrix(y_test, clf3.predict(X_test))  

array([[290,  23],
       [ 21,  37]])

### Ejercicio 3.2: Ajuste de Hiperparámetros

Seleccionar valores para los hiperparámetros principales del DecisionTreeClassifier. Como mínimo, probar diferentes criterios de partición (criterion), profundidad máxima del árbol (max_depth), y cantidad mínima de samples por hoja (min_samples_leaf).

Para ello, usar grid-search y 5-fold cross-validation sobre el conjunto de entrenamiento para explorar muchas combinaciones posibles de valores.

Reportar accuracy promedio y varianza para todas las configuraciones.

Para la mejor configuración encontrada, evaluar sobre el conjunto de **entrenamiento** y sobre el conjunto de **evaluación**, reportando:
- Accuracy
- Precision
- Recall
- F1
- matriz de confusión


Documentación:
- https://scikit-learn.org/stable/modules/grid_search.html
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
# Definimos el espacio de parámetros
parameters = {'criterion': ('gini','entropy'),
              'max_depth': (5,6,7,8,9,10),
              'min_samples_leaf': (2,3,4,5)}

# Creamos el clasificador 'clf' fijando la semilla aleatoria
clf3 = DecisionTreeClassifier(random_state=0)

# Creamos el clasificador 'clf4' usando GridSearchCV
cv2 = GridSearchCV(clf3,parameters,cv=5)

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
cv2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': (5, 6, 7, 8, 9, 10),
                         'min_samples_leaf': (2, 3, 4, 5)})

In [ ]:
# Reportamos accuracy promedio y varianza para todas las configuraciones.
means = cv2.cv_results_['mean_test_score']
stds = cv2.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, cv2.cv_results_['params']):
    print("Exactitud: %0.2f (+/-%0.02f) para los parámetros %r" % (mean, std ** 2, params))

In [ ]:
# Vemos cuáles son los mejores parámetros
cv2.best_params_

{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 2}

In [ ]:
# Armamos el clasificador con los mejores parámetros encontrados
clf4 = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_leaf=2, random_state=0)

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
clf4.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=2, random_state=0)

#### Accuracy, precision, recall, F1

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
Acc_Train4 = accuracy_score( y_train , clf4.predict(X_train) )

# Evaluamos sobre el conjunto de validación
Acc_Test4 = accuracy_score( y_test , clf4.predict(X_test) )

# Evaluamos sobre el conjunto de entrenamiento
Pre_Train4 = precision_score(y_train, clf4.predict(X_train), average='micro')

# Evaluamos sobre el conjunto de validacion
Pre_Test4 = precision_score(y_test, clf4.predict(X_test), average='micro')

# Evaluamos sobre el conjunto de entrenamiento
Rec_Train4 = recall_score(y_train, clf4.predict(X_train))

# Evaluamos sobre el conjunto de validacion
Rec_Test4 = recall_score(y_test, clf4.predict(X_test) ) 

# Evaluamos sobre el conjunto de entrenamiento
F1_Train4 = f1_score(y_train, clf4.predict(X_train), average='weighted')

# Evaluamos sobre el conjunto de validacion
F1_Test4= f1_score(y_test, clf4.predict(X_test), average='weighted')

print("Acurracy for train vlues:", Acc_Train4)
print("Acurracy for test vlues:", Acc_Test4)
print("Precision for train vlues:",Pre_Train4)
print("Precision for test vlues:", Pre_Test4)
print("Recall for train vlues:",Rec_Train4)
print("Recall for train vlues:", Rec_Test4)
print("F1 for train vlues:",F1_Train4)
print("F1 for train vlues:",F1_Test4)

Acurracy for train vlues: 0.9501011463250169
Acurracy for test vlues: 0.8975741239892183
Precision for train vlues: 0.9501011463250169
Precision for test vlues: 0.8975741239892183
Recall for train vlues: 0.7131474103585658
Recall for train vlues: 0.5172413793103449
F1 for train vlues: 0.946747625810616
F1 for train vlues: 0.8895990835101178


#### Matriz de confusión

In [ ]:
# Evaluamos sobre el conjunto de entrenamiento
confusion_matrix(y_train, clf4.predict(X_train))

array([[1230,    2],
       [  72,  179]])

In [ ]:
# Evaluamos sobre el conjunto de validacion
confusion_matrix(y_test, clf4.predict(X_test))  

array([[303,  10],
       [ 28,  30]])